### ISSUE TITLE
incompatible cakephp 3.1.14

### ISSUE THREAD

**Issue by fxgit** [QueenCityCodeFactory/CakeSoap#1]
In requirements says CakePHP 3.x but if try install on a old cakephp(3.1.14) app get this error

```
 Problem 1
    - queencitycodefactory/cakesoap 3.3.1 requires cakephp/cakephp >=3.2.0 ....
```

**Comment by darensipes** [comment]
Thanks for letting us know. We have fixed the documentation and adjusted the requirements in the composer.json.
