### ISSUE TITLE
Expose more Soap options to developer

### ISSUE THREAD

**Issue by dmromanov** [QueenCityCodeFactory/CakeSoap#3]
As a developer I need more control on SoapClient behavior. Change "User Agent", caching, compression and other settings.

Following SoapClient options needs to be exposed to plugin users:
```
proxy_host
proxy_port
proxy_login
proxy_password
local_cert
passphrase
compression
encoding
classmap
exceptions
connection_timeout
typemap
cache_wsdl
user_agent
features
keep_alive
ssl_method
```

Full list of SoapClient options can be found here http://php.net/manual/en/soapclient.soapclient.php

To simplify support, I suggest to expose SoapClient options as prefixed options, e.g. `soap_*`, `soap_compression`.

**Comment by darensipes** [comment]
Fixed in latest update
