### ISSUE TITLE
error Call to undefined method CakeSoap\Network\CakeSoap::setConfig() 

### ISSUE THREAD

**Issue by Omarmaste** [QueenCityCodeFactory/CakeSoap#4]
Please helpme..

Call to undefined method CakeSoap\Network\CakeSoap::setConfig() 
File /var/www/html/AloAurora/vendor/queencitycodefactory/cakesoap/src/Network/CakeSoap.php
Line: 86 

	$soap = new CakeSoap([
		        'wsdl' => 'https://domain/wsdl/customer.wsdl',
		        'userAgent' => 'SoapClient'
		        'uri' => 'http://domain/soap/',
        		'login' => 'xxx',
        		'password' => 'xxx',
		    ]);
			$action = 'get_xdrs';
		    $response = $soap->sendRequest($action, [
		        'SomeData' => [
		            'i_customer' => '270086',
		            'from_date' => '2018-06-01 00:00:00',
		            'to_date' => '2018-06-30 23:59:59',
		            'limit' => '10'		            
		        ]
		    ]);

**Comment by darensipes** [comment]
What version of CakePHP are you using?

'$this->setConfig($config)' on line 86 uses Cake's InstanceConfigTrait.

**Comment by Omarmaste** [comment]
version is

Welcome to CakePHP v3.1.14 Console
---------------------------------------------------------------
App : src
Path: /var/www/html/Aurora/src/
PHP : 5.6.37

what mean that use Cake's InstanceConfigTrait.?

**Comment by darensipes** [comment]
I think you need to either downgrade CakeSoap or Upgrade your version of CakePHP to 3.5+

In the file /var/www/html/AloAurora/vendor/queencitycodefactory/cakesoap/src/Network/CakeSoap.php it is using a cake library InstanceConfigTrait for $this->setConfig(). In the past it was just $this->config(). I suspect that the version of CakePHP you are using uses $this->config().

In your composer.json you could downgrade CakeSoap to an earlier version.

**Comment by Omarmaste** [comment]
ready, i install ws sucess!!
Installing cakephp/app (3.6.5)
  - Installing cakephp/app (3.6.5): Loading from cache
Created project in Aurora

connecting with ws on soap, but it erro about xml 
looks like we got no XML document Cake\Core\Exception\Exception ;(
